ReinaS-64892/TexTransTool

- Editor/Decal/SimpleDecalEditor.cs
- Runtime/ComputeShaders/BlendTexture.compute
- Runtime/ComputeShaders/BlendTextureHelper.hlsl
- Runtime/Decal/RealTimeSimpleDecalPreview.shader
- Runtime/Decal/RealTimeSimpleDecalPreview.shader.meta
- Runtime/Decal/SimpleDecal.cs
> Create simple decal realtime preview

- Editor/TexturAtlas/TexTransAtlasSetEditor.cs
- Runtime/TexturAtlas/AtlasSet.cs
- Runtime/TexturAtlas/IslandUtils.cs
- Runtime/TexturAtlas/TexturAtlasCompiler.cs
- Runtime/Utils.cs
> Atlas set uv scale offset

- Editor/Decal/AbstractDecalEditor.cs
- Editor/Decal/Curve/CurveDecalEditor.cs
- Editor/Decal/CylindricalDecalEditor.cs
- Editor/Decal/NailEditorEditor.cs
- Editor/Decal/NailEditorEditor.cs.meta
- Editor/Decal/SimpleDecalEditor.cs
- Runtime/Decal/AbstractDecal.cs
- Runtime/Decal/AbstructSingleDecal.cs
- Runtime/Decal/AbstructSingleDecal.cs.meta
- Runtime/Decal/Curve/CurveDecal.cs
- Runtime/Decal/Curve/CylindricalCurveDecal.cs
- Runtime/Decal/CylindricalDecal.cs
- Runtime/Decal/NailEditor.cs
- Runtime/Decal/NailEditor.cs.meta
- Runtime/Decal/NailOffsetData.cs
- Runtime/Decal/NailOffsetData.cs.meta
- Runtime/Decal/SimpleDecal.cs
> Create nail editor

- Editor/TexturAtlas/AtlasTextureEditor.cs
- Editor/TextureTransformerEditor.cs
- Runtime/AssetSaveHelper.cs
- Runtime/AvatarDomainDefinition.cs
- Runtime/TexTransGroup/AbstractTexTransGroup.cs
- Runtime/TexturAtlas/AtlasSetting.cs
- Runtime/TexturAtlas/AtlasSetting.cs.meta
- Runtime/TexturAtlas/AtlasTexture.cs
- Runtime/TexturAtlas/AtlasTextureDataContainer.cs
- Runtime/TexturAtlas/FineSetting.meta
- Runtime/TexturAtlas/FineSetting/Compless.cs
- Runtime/TexturAtlas/FineSetting/Compless.cs.meta
- Runtime/TexturAtlas/FineSetting/DefaultCompless.cs
- Runtime/TexturAtlas/FineSetting/DefaultCompless.cs.meta
- Runtime/TexturAtlas/FineSetting/IFineSetting.cs
- Runtime/TexturAtlas/FineSetting/IFineSetting.cs.meta
- Runtime/TexturAtlas/FineSetting/Initialize.cs
- Runtime/TexturAtlas/FineSetting/Initialize.cs.meta
- Runtime/TexturAtlas/FineSetting/RefarensCopy.cs
- Runtime/TexturAtlas/FineSetting/RefarensCopy.cs.meta
- Runtime/TexturAtlas/FineSetting/Remove.cs
- Runtime/TexturAtlas/FineSetting/Remove.cs.meta
- Runtime/TexturAtlas/FineSetting/Resize.cs
- Runtime/TexturAtlas/FineSetting/Resize.cs.meta
> Create atlas texture fine setting

- Runtime/AssetSaveHelper.cs
- Runtime/AvatarDomainAsset.cs
- Runtime/AvatarDomainDefinition.cs
- Runtime/BlendTexture/TextureBlender.cs
- Runtime/BlendTexture/TextureLayerUtil.cs
- Runtime/Island/IslandUtils.cs
- Runtime/TexturAtlas/AtlasTexture.cs
- Runtime/TexturAtlas/AtlasTextureDataContainer.cs
- Runtime/TransTexture/TransTexture.cs
> Add avatar domain asset manage

- Editor/Decal/AbstractDecalEditor.cs
- Editor/Decal/CylindricalDecalEditor.cs
- Editor/Decal/NailEditorEditor.cs
- Editor/Decal/SimpleDecalEditor.cs
- Editor/PropatyNameEditorUtili.cs
- Editor/PropatyNameEditorUtili.cs.meta
- Editor/TexturAtlas/AtlasTextureEditor.cs
- Editor/TextureTransformerEditor.cs
- Runtime/Decal/AbstractDecal.cs
- Runtime/PropatyName.cs
- Runtime/PropatyName.cs.meta
- Runtime/ShaderSupport/DefaultShaderSupprot.cs
- Runtime/ShaderSupport/DefaultShaderSupprot.cs.meta
- Runtime/ShaderSupport/IShaderSupport.cs
- Runtime/ShaderSupport/ShaderSupportUtil.cs
- Runtime/ShaderSupport/liltoon/liltoonSupport.cs
- Runtime/TexturAtlas/AtlasSetting.cs
> Improved target propaty name

- TestCode.meta
- TestCode/TransTextureTest.cs
- TestCode/TransTextureTest.cs.meta
- TestCode/net.ra64.textranstool.testcode.asmdef
- TestCode/net.ra64.textranstool.testcode.asmdef.meta
> Create test code

- Editor/TextureAtlas/AtlasTextureEditor.cs
Some slight clarity adjustments
> fine settings -> texture fine tuning

- TexTransCore/TransTextureCore/ShaderAsset/TransTextureShader.shader
on metal, geometry shader not supported
> feat: metal support

- CHANGELOG.md
- Editor/Decal/AbstractDecal.cs
[TTT-DestructiveTextureUtilities](https://github.com/ReinaS-64892/TTT-DestructiveTextureUtilities) がやるべき案件
> Remove: ExtractDecal

- CHANGELOG.md
- TexTransCore/BlendTexture/ShaderAsset/BlendColor.hlsl
> Fix: LinierLight And Addition

- CHANGELOG.md
- TexTransCore/BlendTexture/ShaderAsset/BlendColor.hlsl
> Fix: VividLight

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasIsland.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/IslandRelocator/NFDHPlasFC.cs
- Runtime/TextureAtlas/TextureFineTuning/Resize.cs
- TexTransCore/Island/IslandUtility.cs
keep IslandUVTile は作ってみたがテストしていない...
> feat : height deflate

- CHANGELOG.md
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/TextureAtlas/AtlasTexture.cs
> chore: add Warning MoreMaterialSlotThanSubMesh

- Runtime/TextureAtlas/AtlasTexture.cs
- TexTransCore/TransTextureCore/TriangleIndex.cs
とりあえず TriangleIndex に対して直接 SelectMany しないことで高速化
> opti: cross submesh island merging

- CHANGELOG.md
- Editor/NDMFNotExistWarning.meta
- Editor/NDMFNotExistWarning/NDMFNotExistWarning.cs
- Editor/NDMFNotExistWarning/NDMFNotExistWarning.cs.meta
- Editor/NDMFNotExistWarning/net.rs64.tex-trans-tool.editor.ndmf-not-exist-waring.asmdef
- Editor/NDMFNotExistWarning/net.rs64.tex-trans-tool.editor.ndmf-not-exist-waring.asmdef.meta
> chore: add NDMF Not Exist Warning

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasShaderSupport/AtlasShaderSupportUtils.cs
context: https://misskey.niri.la/notes/9toqf2dxo8
全く再現ができず、おそらく回避できるであろうの方法。
> fix: exception when not exist DefaultSupporter

- CHANGELOG.md
- TexTransCore/Utils/RendererUtility.cs
> fix: exception occur when no exist MeshFilter

- Editor/Inspector/Decal/SingleGradationDecalEditor.cs
- Runtime/Decal/Gradation/SingleGradationDecal.cs
> feat: Add advanced settings to `SingleGradationDecal`

- CHANGELOG-EXPERIMENTAL.md
- CHANGELOG.md
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Inspector/TextureAtlas/TextureFineTuningManager.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/TextureAtlas/AtlasSetting.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/TextureFineTuning/Resize.cs
> Atlas texture texture auto tune

- CHANGELOG-EXPERIMENTAL.md
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Inspector/TextureAtlas/TextureFineTuningManager.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/TextureAtlas/AtlasSetting.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/TextureFineTuning/MergeTexture.cs
- Runtime/TextureAtlas/TextureFineTuning/MergeTexture.cs.meta
- Runtime/TextureAtlas/TextureFineTuning/TexFineTuningTarget.cs
- TexTransCore/Utils/TextureUtility.cs
> feat: MergeTexture

- CHANGELOG-EXPERIMENTAL.md
- CHANGELOG.md
- Editor/Domain/TextureManager.cs
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/CommonComponent/TextureConfigurator.cs
- Runtime/IDomain.cs
- Runtime/TextureAtlas/AtlasContext.cs
- Runtime/TextureAtlas/AtlasSetting.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/TextureFineTuning/Compress.cs
> feat: Determine on a compression format with based on transparency.

- CHANGELOG.md
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
> feat: display Material select candidates by Material grouping

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasShaderSupport/AtlasScriptableObject/AtlasShaderSupportScriptableObject.cs
- Runtime/TextureAtlas/AtlasTexture.cs
> fix: replace texture only if constraint are valid

- CHANGELOG.md
- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
> Improve new game object and add ttt component

- CHANGELOG-EXPERIMENTAL.md
- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
- Runtime/MultiLayerImage/SpecialLayer/ShaderAssets/SpecialLayerShaders.cs
- Runtime/MultiLayerImage/SpecialLayer/ShaderAssets/YAxisFixedGradient.shader
- Runtime/MultiLayerImage/SpecialLayer/ShaderAssets/YAxisFixedGradient.shader.meta
- Runtime/MultiLayerImage/SpecialLayer/YAxisFixedGradientLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/YAxisFixedGradientLayer.cs.meta
> feat: YAsixFixedGradientLayer

- CHANGELOG-EXPERIMENTAL.md
- Editor/Inspector/Decal/AbstractDecalEditor.cs
- Editor/Inspector/Decal/SimpleDecalEditor.cs
- Editor/Inspector/Decal/SingleGradationDecalEditor.cs
- Runtime/Decal/SimpleDecal.cs
- Runtime/MultiLayerImage/MultiLayerImageCanvas.cs
close #442 close #492 
PreProcessor とは言えない違うものにはなっちゃったけど、一応グラデーションの生成もできるようになったし、MLICの高度な編集をそのままデカールにできるよ！やったね！
すぐかなり大幅な変更加えそうな...やばやば実験的機能だけどまぁ...うん
> feat: OverrideDecalTextureWithMultiLayerImageCanvas

- CHANGELOG.md
- Editor/Domain/TextureManager.cs
> fix: occur ArgumentNullException when CompressDeferred on Build

- CHANGELOG.md
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/TextureAtlas/AtlasSetting.cs
- Runtime/TextureAtlas/AtlasTexture.cs
> feat: stabilize PixelNormalize

- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
- Runtime/MultiLayerImage/SpecialLayer/ColorizeLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/ColorizeLayer.cs.meta
- Runtime/MultiLayerImage/SpecialLayer/ShaderAssets/ColorizeShader.shader
- Runtime/MultiLayerImage/SpecialLayer/ShaderAssets/ColorizeShader.shader.meta
- Runtime/MultiLayerImage/SpecialLayer/ShaderAssets/SpecialLayerShaders.cs
- TexTransCore/BlendTexture/ShaderAsset/HSL.hlsl
- TexTransCore/BlendTexture/ShaderAsset/HSL.hlsl.meta
- TexTransCore/BlendTexture/ShaderAsset/HSV.hlsl
> feat: ColorizeLayer

- CHANGELOG.md
- Editor/NDMFNotExistWarning/NDMFNotExistWarning.cs
- Editor/NDMFNotExistWarning/net.rs64.tex-trans-tool.editor.ndmf-not-exist-waring.asmdef
> fix: ndmf not supported version warning

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/TextureFineTuning/ColorSpace.cs
- Runtime/TextureAtlas/TextureFineTuning/Compress.cs
- Runtime/TextureAtlas/TextureFineTuning/DiscardAlphaChannel.cs
- Runtime/TextureAtlas/TextureFineTuning/ITextureFineTuning.cs
- Runtime/TextureAtlas/TextureFineTuning/MergeTexture.cs
- Runtime/TextureAtlas/TextureFineTuning/MipMapRemove.cs
- Runtime/TextureAtlas/TextureFineTuning/ReferenceCopy.cs
- Runtime/TextureAtlas/TextureFineTuning/Remove.cs
- Runtime/TextureAtlas/TextureFineTuning/Resize.cs
- Runtime/TextureAtlas/TextureFineTuning/TexFineTuningTarget.cs
> fix: incorrect delegation of compress value

- CHANGELOG.md
- Editor/Inspector/Decal/SimpleDecalEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/Decal/SimpleDecal.cs
> change: rename to BackCulling

- Runtime/TextureAtlas/AtlasContext.cs
This saves ~200ms processing my hair mesh.
> perf: index vertices in a Dictionary to avoid O(n^2) behavior

- CHANGELOG-EXPERIMENTAL.md
- CHANGELOG.md
- Editor/Inspector/PowerOfTwoDrawer.cs
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/TextureAtlas/AtlasSetting.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/IslandRelocator/AtlasIslandRelocatorObject.cs
- Runtime/TextureAtlas/IslandRelocator/IAtlasIslandRelocator.cs
- Runtime/TextureAtlas/IslandRelocator/IslandRelocationManager.cs
- Runtime/TextureAtlas/IslandRelocator/NFDHPlasFC.cs
may close #717 
縦の解像度を指定した値によって除算します。
見た感じ動作していますが、それっぽい場所を変更しただけなので正しい実装があれば教えてくれると助かります。
UIへの露出は一旦していません。
> feat: HeightDenominator at AtlasTexture

- CHANGELOG.md
- Editor/Domain/TextureManager.cs
- Editor/Utils/TextureUtility.cs
- Editor/csc.rsp
> fix: do not working if System.Drawing does not exist

- Runtime/Average.compute
- Runtime/Average.compute.meta
- Runtime/AverageIgnoreAlpha.compute
- Runtime/AverageIgnoreAlpha.compute.meta
- Runtime/MipMapUtility.cs
> fix: MipMapUtility is broken

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasShaderSupport/liltoon/liltoonAtlasSupport.asset
> fix: incorrect to MatCap texture the atlas define

- CHANGELOG.md
- Editor/Build/AvatarBuildUtils.cs
- Editor/Domain/RenderersDomain.cs
- Editor/NDMF/NDMFDomain.cs
- Runtime/IDomain.cs
- Runtime/Utils/MaterialUtility.cs
> feat: GetMutable

- Editor/MultiLayerImageImporter/CanvasImportedImagePreviewManager.cs
> fix: CanvasImportedImagePreview crashes on active scene change

- CHANGELOG-EXPERIMENTAL.md
- Editor/Inspector/MaterialConfiguratorEditor.cs
- Editor/Inspector/MaterialConfiguratorEditor.cs.meta
- Editor/Inspector/MaterialPropertyDrawer.cs
- Editor/Inspector/MaterialPropertyDrawer.cs.meta
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
- Runtime/Common/MaterialProperty.cs
- Runtime/Common/MaterialProperty.cs.meta
- Runtime/CommonComponent/MaterialConfigurator.cs
- Runtime/CommonComponent/MaterialConfigurator.cs.meta
related to #787 
コンポーネントを分け、Runtime実装に変更しました。
> feat: MaterialConfigurator

- Editor/Inspector/MaterialConfiguratorEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/CommonComponent/MaterialConfigurator.cs
- Runtime/IDomain.cs
closes #794, #795 
そのほかにPrefab Revert/ApplyがConfigured Materialに反映されない問題も修正しています
> fix: MaterialConfigurator behavior

- Editor/Inspector/MaterialConfiguratorEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Runtime/CommonComponent/MaterialConfigurator.cs
- Runtime/IDomain.cs
> feat: OverrideUtility for MaterialConfigurator

- CHANGELOG.md
- Editor/Domain/TextureManager.cs
- Editor/EditorProcessor/EditorProcessorAttribute.cs
- Editor/EditorProcessor/MaterialOverrideTransferProcessor.cs
- Editor/Inspector/DomainTextureSelector.cs
- Editor/Inspector/MaterialConfiguratorEditor.cs
- Editor/Inspector/TextureTransformerEditor.cs
- Editor/NDMF/NegotiateAAOPass.cs
- Editor/NDMF/TexTransDomainFilter.cs
- Editor/Utils/TexTransBehaivorUtility.cs
- Runtime/Common/TextureSelector.cs
- Runtime/CommonComponent/MaterialConfigurator.cs
- Runtime/CommonComponent/TextureBlender.cs
- Runtime/CommonComponent/TextureConfigurator.cs
- Runtime/Decal/DecalContext.cs
- Runtime/Decal/DecalRendererSelector.cs
- Runtime/Decal/Gradation/SingleGradationDecal.cs
- Runtime/Decal/SimpleDecal.cs
- Runtime/IDomain.cs
- Runtime/MultiLayerImage/MultiLayerImageCanvas.cs
- Runtime/TexTransRuntimeBehavior.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/Utils/MaterialUtility.cs
- Runtime/Utils/MeshUtility.cs
- Runtime/Utils/RendererUtility.cs
> feat: AffectingRendererTargeting

- Editor/NDMF/NDMFPreviewMaterialPool.cs
> fix: forgetting to reset the shader on ret

- CHANGELOG.md
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending.meta
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaAddition.ttblend
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaAddition.ttblend.meta
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaDivision.ttblend
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaDivision.ttblend.meta
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaMultiply.ttblend
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaMultiply.ttblend.meta
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaReplace.ttblend
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaReplace.ttblend.meta
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaSubtract.ttblend
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/AlphaSubtract.ttblend.meta
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/ColorReplace.ttblend
- TexTransCore/ShaderAssets/Blendings/ExtraColorBlending/ColorReplace.ttblend.meta
> feat: ExtraColorBlending

- Editor/EditorProcessor/EditorProcessorAttribute.cs
- Editor/EditorProcessor/MaterialOverrideTransferProcessor.cs
- Editor/NDMF/TexTransDomainFilter.cs
- Editor/Utils/TexTransBehaivorUtility.cs
- Runtime/CommonComponent/MaterialModifier.cs
- Runtime/CommonComponent/MaterialOverrideTransfer.cs
- Runtime/TexTransRuntimeBehavior.cs
> Optimize ndmf preview

- Editor/NDMF/TexTransDomainFilter.cs
- Runtime/IDomain.cs
> fix: Exception occur when contains null material at renderer.

- CHANGELOG.md
- Editor/NDMF/NDMFPreviewMaterialPool.cs
- Editor/NDMF/TexTransDomainFilter.cs
謎に無限ループしたり ... しなくなったりと不安定なのでいったん無効化する。
> change: disable NDMFAffectingRendererTargeting

- CHANGELOG-EXPERIMENTAL.md
- Editor/Inspector/ColorDifferenceChangerEditor.cs
- Editor/Inspector/Decal/DecalRendererSelectorEditor.cs
- Editor/Inspector/Decal/SimpleDecalEditor.cs
- Editor/Inspector/Decal/SingleGradationDecalEditor.cs
- Editor/Inspector/TextureBlenderEditor.cs
- Runtime/CommonComponent/ColorDifferenceChanger.cs
- Runtime/CommonComponent/TextureBlender.cs
- Runtime/Decal/DecalContext.cs
- Runtime/Decal/Gradation/SingleGradationDecal.cs
- Runtime/Decal/SimpleDecal.cs
- Runtime/IDomain.cs
- Runtime/ITexTransToolForUnity.cs
- Runtime/MultiLayerImage/AbstractImageLayer.cs
- Runtime/MultiLayerImage/AbstractLayer.cs
- Runtime/MultiLayerImage/AsLayer.cs
- Runtime/MultiLayerImage/LayerFolder.cs
- Runtime/MultiLayerImage/MultiLayerImageCanvas.cs
- Runtime/MultiLayerImage/RasterImportedLayer.cs
- Runtime/MultiLayerImage/RasterLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/ColorizeLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/HSLAdjustmentLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/HSVAdjustmentLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/LevelAdjustmentLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/SelectiveColorAdjustmentLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/SolidColorLayer.cs
- Runtime/MultiLayerImage/SpecialLayer/UnityGradationMapLayer.cs
- TexTransCore/MultiLayerImageCanvas/RasterLayer.cs
- TexTransCore/TransTexture/TransMappingUtility.cs
> Feat decal as layer

- CHANGELOG-EXPERIMENTAL.md
- Runtime/Decal/Gradation/SingleGradientSpace.cs
- Runtime/Decal/ParallelProjection/IslandSelectToPPFilter.cs
- Runtime/MultiLayerImage/IslandSelectAsLayerMask.cs
- Runtime/MultiLayerImage/IslandSelectAsLayerMask.cs.meta
- TexTransCore/ShaderAssets/TransTexture/PolygonMask.meta
- TexTransCore/ShaderAssets/TransTexture/PolygonMask/PolygonMask.ttcomp
- TexTransCore/ShaderAssets/TransTexture/PolygonMask/PolygonMask.ttcomp.meta
- TexTransCore/TransTexture/PolygonMask.cs
- TexTransCore/TransTexture/PolygonMask.cs.meta
> feat: IslandSelectAsLayerMask

- Editor/Domain/TextureManager.cs
- Editor/Inspector/TextureConfiguratorEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Editor/TextureStack.cs
- Runtime/CommonComponent/ColorDifferenceChanger.cs
- Runtime/CommonComponent/NearTransTexture.cs
- Runtime/CommonComponent/TextureConfigurator.cs
- Runtime/Decal/Gradation/SingleGradationDecal.cs
- Runtime/ITexTransToolForUnity.cs
- Runtime/TTCEUnityWithTTT4Unity.cs
- Runtime/TextureAtlas/TextureFineTuning/Compress.cs
- TTCE-Unity/TTRt2.cs
- TexTransCore/ITTEngine.cs
> Re implement tex cfg and output texture color space is gumma

- CHANGELOG.md
- Editor/Inspector/Decal/SingleGradationDecalEditor.cs
- Editor/Inspector/IslandSelector/AbstractIslandSelectorEditor.cs
- Runtime/IslandSelect/AbstructIslandSelector.cs
- Runtime/IslandSelect/BoxIslandSelector.cs
- Runtime/IslandSelect/IslandSelectorAND.cs
- Runtime/IslandSelect/IslandSelectorNOT.cs
- Runtime/IslandSelect/IslandSelectorOR.cs
- Runtime/IslandSelect/IslandSelectorXOR.cs
- Runtime/IslandSelect/PinIslandSelector.cs
- Runtime/IslandSelect/SphereIslandSelector.cs
> feat: SGD and IslandSelector are mark as stable

- CHANGELOG-EXPERIMENTAL.md
- Editor/Inspector/ParallelProjectionWithLilToonDecalEditor.cs
- Editor/Inspector/ParallelProjectionWithLilToonDecalEditor.cs.meta
- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
- Runtime/CommonComponent/ParallelProjectionWithLilToonDecal.cs
- Runtime/CommonComponent/ParallelProjectionWithLilToonDecal.cs.meta
- Runtime/Decal/MeshData.cs
- Runtime/Decal/SimpleDecal.cs
- Runtime/Decal/TriangleFilterUtility.cs
- Runtime/IDomain.cs
> Parallel projection with lil toon decal

- Editor/Inspector/Decal/DistanceGradationDecalEditor.cs
- Editor/Inspector/Decal/SimpleDecalEditor.cs
- Editor/Inspector/Decal/SingleGradationDecalEditor.cs
- Editor/Inspector/IslandSelector/AimIslandSelectorEditor.cs
- Editor/Inspector/MaterialModifierEditor.cs
- Editor/Inspector/MultiLayerImage/AbstractLayerEditor.cs
- Editor/Inspector/MultiLayerImage/AsLayerEditor.cs
- Editor/Inspector/MultiLayerImage/MultiLayerImageCanvasEditor.cs
- Editor/Inspector/ParallelProjectionWithLilToonDecalEditor.cs
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Inspector/TextureBlenderEditor.cs
- Editor/Inspector/TextureTransformerEditor.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Editor/Migration/AAOMigrator.cs
- TTCE-Unity/TTRt2.cs
close #860 
ボタンに表示されるテキストが ... 何か日本語に敗北してる気がするけど、ないよりはあった方が便利だから ...
> Improve migration

- Editor/Build/AvatarBuildUtils.cs
> fix: failed to destroy component

- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
- Runtime/MultiLayerImage/SpecialLayer/YAxisFixedGradientLayer.cs
Y**Asix**FixedGradientLayerをY**Axis**FixedGradientLayerに修正しています。
> fix: typo of YAsixFixedGradientLayer

- CHANGELOG.md
- Runtime/Decal/SimpleDecal.cs
- Runtime/Decal/TriangleFilterUtility.cs
> fix: wrong implementation aabb culling

- Editor/Build/AvatarBuildUtils.cs
- Editor/Domain/RenderersDomain.cs
- Editor/Domain/TextureManager.cs
- Editor/Inspector/MultiLayerImage/AbstractLayerEditor.cs
- Editor/Inspector/MultiLayerImage/MultiLayerImageCanvasEditor.cs
- Editor/Inspector/TextureAtlas/TextureFineTuningManager.cs
- Editor/MultiLayerImageImporter/CanvasImportedImagePreviewManager.cs
- Editor/NDMF/NodeExecuteDomain.cs
- Editor/Preview/RealTime/PreviewStackManager.cs
- Editor/Preview/RealTime/RealTimePreviewDomain.cs
- Runtime/IDomain.cs
- Runtime/ITexTransToolForUnity.cs
- Runtime/TTCEUnityWithTTT4Unity.cs
- Runtime/TTCEWithTTTFUInterfaceDebug.cs
- Runtime/TTCEWithTTTFUInterfaceDebug.cs.meta
- Runtime/Utils/TextureUtility.cs
- TTCE-Unity/ComputeObjectUtility.cs
- TTCE-Unity/TTCEUnity.cs
- TTCE-Unity/TTUnityComputeHandler.cs
- TTT-PSDImporter/Runtime/PSDImportedRasterImage.cs
- TexTransCore/ITTComputeHundler.cs
- TexTransCore/ITTObject.cs
- TexTransCore/ITTTexture.cs
- TexTransCore/MultiLayerImageCanvas/CanvasContext.cs
- TexTransCore/MultiLayerImageCanvas/LayerFolder.cs
- TexTransCore/TTCEInterfaceDebug.cs
- TexTransCore/TTCEInterfaceDebug.cs.meta
> Fix memory leak

- CHANGELOG.md
- Editor/NDMF/NDMFPreviewMaterialPool.cs
> fix: forgetting to copy shader-keywords

- Editor/Inspector/MaterialModifierEditor.cs
- Runtime/CommonComponent/MaterialModifier.cs
Utility及びRecordingMaterialの更新時にShaderの変更を加味していなかったのを修正しました。
> fix: MaterialModifierEditor

- CHANGELOG-EXPERIMENTAL.md
- Editor/Inspector/Decal/DecalRendererSelectorEditor.cs
- Editor/Inspector/TargetObjectSelector.cs
- Editor/Inspector/TargetObjectSelector.cs.meta
- Editor/Inspector/TextureAtlas/AtlasTextureEditor.cs
- Editor/Inspector/TextureAtlas/IslandSizePriorityTunerEditor/SetFromMaterialDrawer.cs
- Editor/Inspector/UVCopyEditor.cs
- Editor/Inspector/UVCopyEditor.cs.meta
- Editor/Migration/V6/AtlasTextureV6.cs
- Editor/OtherMenuItem/NewGameObjectAndAddTTTComponent.cs
- Runtime/CommonComponent/UVCopy.cs
- Runtime/CommonComponent/UVCopy.cs.meta
- Runtime/Obsolete/AtlasTextureObsoletes.cs
- Runtime/Utils/MeshUtility.cs
> feat: TTT UVCopy

- TTCE-Unity/TTCEUnity.cs
- TTCE-Unity/TTUnityComputeHandler.cs
- TTT-PSDImporter/Runtime/PSDImportedRasterImage.cs
- TTT-PSDImporter/Runtime/PSDImportedRasterMaskImage.cs
> Fix invalid stride

- CHANGELOG.md
- Editor/Inspector/MultiLayerImage/MultiLayerImageCanvasEditor.cs
- Editor/Inspector/TextureSelectorDrawer.cs
- Editor/Migration/V6/AtlasTextureV6.cs
- Editor/Migration/V6/TTTV6Migrator.cs
- Editor/Migration/V6/TextureSelectorV6.cs
- Editor/Migration/V6/TextureSelectorV6.cs.meta
- Runtime/Common/TextureSelector.cs
- Runtime/MultiLayerImage/MultiLayerImageCanvas.cs
- Runtime/TextureAtlas/AtlasTexture.cs
> Remve relateve mode

- CHANGELOG.md
- Runtime/Decal/Gradation/DistanceGradationDecal.cs
- Runtime/Decal/Gradation/SingleGradationDecal.cs
- Runtime/Decal/SimpleDecal.cs
> remove: Decal.HighQualityPadding

- CHANGELOG.md
- Editor/Domain/TextureManager.cs
- Runtime/IDomain.cs
> feat: AG to RG or RG to AG conversion when load and compress for Normal Map.

- Editor/Config/TTTProjectConfig.cs
- Editor/Inspector/CommonDrawer/AffectVRAMAttributeDrawer.cs
- Editor/Inspector/TexTransMonoBaseEditor.cs
- Editor/Localize/Localize.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
- Editor/Menu/TTTConfigMenu.cs
> feat: opt-out for AffectVRAMIcon and Experimental warnings

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasMeshSourceContext.cs
- TestCode/AtlasTexture/RetainSubMeshCountWhenNormalizing.cs
- TestCode/AtlasTexture/RetainSubMeshCountWhenNormalizing.cs.meta
- TestCode/AtlasTexture/SmallerMaterialSlotThanSubMesh.cs
- TestCode/AtlasTexture/SmallerMaterialSlotThanSubMesh.cs.meta
- TestCode/AtlasTexture/SmallerMaterialSlotThanSubMesh.prefab
- TestCode/AtlasTexture/SmallerMaterialSlotThanSubMesh.prefab.meta
> Less matslot

- CHANGELOG-EXPERIMENTAL.md
- Editor/NDMF/PreviewUtility/EverythingUnlitTexture.cs
- Editor/NDMF/PreviewUtility/PreviewIslandSelector.cs
> Fix previewutility

- CHANGELOG.md
- Editor/NDMF/AdditionalMaterialsProvider/AdditionalMaterialsProvider.cs
- Editor/NDMF/AdditionalMaterialsProvider/AnimatorMaterialsProvider.cs
- Editor/NDMF/AdditionalMaterialsProvider/MAMaterialsProvider.cs
- Editor/NDMF/NDMFDomain.cs
- Editor/NDMF/TexTransDomainFilter.cs
- Runtime/CommonComponent/UVCopy.cs
- Runtime/IDomain.cs
- Runtime/IslandSelect/MaterialIslandSelector.cs
- Runtime/TextureAtlas/AtlasTexture.cs
- Runtime/TextureAtlas/IslandSizePriortyTuner/SetFromMaterial.cs
> Exception from missing

- CHANGELOG.md
- Editor/Domain/TextureManager.cs
> fix: avoid linear color store when LoadTexture from UnityDiskTexture.

- CHANGELOG.md
- Editor/Inspector/TextureAtlas/TextureFineTuning/CompressTuningDrawer.cs
- Editor/Localize/en_US.po
- Editor/Localize/ja_JP.po
> fix: Compress editor throws exception in unknown target platform.

- CHANGELOG.md
- Runtime/TextureAtlas/AtlasMeshSourceContext.cs
> fix: incorrect temp-renderer position when bake Mesh in AtlasTexture.

- CHANGELOG.md
- Editor/Migration/AAOMigrator.cs
- Editor/Migration/TTTMigratorUtility.cs
> remove: ProjectMigrationDialog

- Editor/TTComputeShaderImporter.cs
内部的な変更であるが、次のバージョンが TTC v0.2.0 を要求するようになる
> feat: avoid error in code editor

- CHANGELOG.md
- Editor/TTComputeShaderImporter.cs
close #976
close #951
Importer の Reimport を強制的に発火させる
> feat: change internal shader importer version

- CHANGELOG.md
- Runtime/Utils/MeshUtility.cs
> fix: NRE occur if contains AAO Remove Mesh and AtlasTexture

- Editor/Build/AvatarBuildUtils.cs
- Editor/NDMF/NDMFPlugin.cs
- Editor/NDMF/TTTPass.cs
- Runtime/CommonComponent/ModificationOnlyTag.cs
- Runtime/CommonComponent/ModificationOnlyTag.cs.meta
- Runtime/TexTransBehavior.cs
> feat: ModificationOnlyTag

- ParserUtility/ParserUtility.cs
related https://github.com/ReinaS-64892/TTT-ClipImporter
> feat: more function in BinarySectionStream
